openapi: 3.0.1
info:
  title: Inventory
  description: Angular haladó tanfolyam - 1.nap
  version: 1.0.0
servers:
  - url: https://autsoftangular.azurewebsites.net/api
paths:
  /Inventory:
    get:
      tags:
        - Inventory
      operationId: GetItems
      parameters:
        - name: PageSize
          in: query
          schema:
            type: integer
            format: int32
            nullable: true
        - name: Page
          in: query
          schema:
            type: integer
            format: int32
            nullable: true
        - name: OrderBy
          in: query
          schema:
            type: string
            nullable: true
        - name: OrderDirection
          in: query
          schema:
            type: integer
            nullable: true
            enum:
              - 1
              - 2
            x-schema:
              $ref: '#/components/schemas/OrderDirection'
          x-schema:
            $ref: '#/components/schemas/OrderDirection'
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagingResultDtoOfItem'
    post:
      tags:
        - Inventory
      operationId: CreateItem
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
        required: true
      responses:
        200:
          description: ""
          content: {}
      x-codegen-request-body-name: value
  /Inventory/{id}:
    get:
      tags:
        - Inventory
      operationId: GetItemsById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
            nullable: false
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
    put:
      tags:
        - Inventory
      operationId: UpdateItem
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
            nullable: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
        required: true
      responses:
        200:
          description: ""
          content: {}
      x-codegen-request-body-name: value
    delete:
      tags:
        - Inventory
      operationId: DeleteItem
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
            nullable: false
      responses:
        200:
          description: ""
          content: {}
  /Inventory/Typeahead/Type:
    get:
      tags:
        - Inventory
      operationId: TypeaheadType
      parameters:
        - name: query
          in: query
          schema:
            type: string
            nullable: true
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
components:
  schemas:
    PagingResultDtoOfItem:
      required:
        - currentPage
        - results
        - totalCount
      type: object
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/Item'
        currentPage:
          type: integer
          format: int32
        totalCount:
          type: integer
          format: int32
    Item:
      required:
        - count
        - countDate
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        description:
          type: string
        countDate:
          type: string
          format: date-time
        count:
          type: integer
          format: int32
        type:
          type: string
        dimension:
          $ref: '#/components/schemas/Dimension'
        price:
          $ref: '#/components/schemas/Price'
    Dimension:
      required:
        - depth
        - height
        - width
      type: object
      properties:
        width:
          type: number
          format: double
        height:
          type: number
          format: double
        depth:
          type: number
          format: double
    Price:
      required:
        - currency
        - value
      type: object
      properties:
        value:
          type: number
          format: double
        currency:
          $ref: '#/components/schemas/Currency'
    Currency:
      type: integer
      description: ""
      enum:
        - 1
        - 2
        - 3
      x-enumNames:
        - EUR
        - USD
        - HUF
    OrderDirection:
      type: integer
      description: ""
      enum:
        - 1
        - 2
      x-enumNames:
        - Asc
        - Desc
